//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Christian Schlegel (schlegel@hs-ulm.de)
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#ifndef COMMROQMEOBJECTS_COMMQOSMETRICS_SERIALIZATION_H_
#define COMMROQMEOBJECTS_COMMQOSMETRICS_SERIALIZATION_H_

#include "CommRoQMEObjects/CommQoSMetricsIDL.hh"

// serialization operator for element CommQoSMetrics
ACE_CDR::Boolean operator<<(ACE_OutputCDR &cdr, const CommRoQMEObjectsIDL::CommQoSMetrics &data);

// de-serialization operator for element CommQoSMetrics
ACE_CDR::Boolean operator>>(ACE_InputCDR &cdr, CommRoQMEObjectsIDL::CommQoSMetrics &data);

#endif /* COMMROQMEOBJECTS_COMMQOSMETRICS_SERIALIZATION_H_ */
