//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Christian Schlegel (schlegel@hs-ulm.de)
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#include "CommRoQMEObjects/CommQoSMetricsCore.hh"

// serialization/deserialization operators
#include "CommRoQMEObjects/CommQoSMetricsSerialization.hh"

// include the hash.idl containing the hash constant
#include "hash.hh"
#include <assert.h>
#include <iostream>

// SmartUtils used in from_xml method
#include "smartKnuthMorrisPratt.hh"

#include <ace/SString.h>

#ifdef ENABLE_HASH
	#include <boost/functional/hash.hpp>
#endif

namespace CommRoQMEObjects 
{
	const char* CommQoSMetricsCore::getCompiledHash()
	{
		return CommRoQMEObjectsIDL::REPO_HASH;
	}
	
	void CommQoSMetricsCore::getAllHashValues(std::list<std::string> &hashes)
	{
		// get own hash value
		hashes.push_back(getCompiledHash());
	}
	
	void CommQoSMetricsCore::checkAllHashValues(std::list<std::string> &hashes)
	{
		// check own hash value
		if (strcmp(getCompiledHash(), hashes.front().c_str()) != 0)
		{
			std::cerr << "###################################################" << std::endl;
			std::cerr << "WARNING: HASHES OF COMMUNICATION OBJECTS MISSMATCH!" << std::endl;
			std::cerr << "CommQoSMetricsCore hash" << std::endl;
			std::cerr << "Expected: " << getCompiledHash() << std::endl;
			std::cerr << "Received: " << hashes.front() << std::endl;
			std::cerr << "###################################################" << std::endl;
		}
		assert(strcmp(getCompiledHash(), hashes.front().c_str()) == 0);
		hashes.pop_front();
		
	}
	
	#ifdef ENABLE_HASH
	size_t CommQoSMetricsCore::generateDataHash(const DATATYPE &data)
	{
		size_t seed = 0;
		
		std::vector<ACE_CString>::const_iterator data_metricNamesIt;
		for(data_metricNamesIt=data.metricNames.begin(); data_metricNamesIt!=data.metricNames.end(); data_metricNamesIt++) {
			boost::hash_combine(seed, std::string(data_metricNamesIt->c_str()));
		}
		std::vector<ACE_CDR::Double>::const_iterator data_valuesIt;
		for(data_valuesIt=data.values.begin(); data_valuesIt!=data.values.end(); data_valuesIt++) {
			boost::hash_combine(seed, *data_valuesIt);
		}
		
		return seed;
	}
	#endif
	
	// default constructor
	CommQoSMetricsCore::CommQoSMetricsCore()
	:	idl_CommQoSMetrics()
	{  
		setMetricNames(std::vector<std::string>());
		setValues(std::vector<double>());
	}

	CommQoSMetricsCore::~CommQoSMetricsCore()
	{  }
	
	void CommQoSMetricsCore::to_ostream(std::ostream &os) const
	{
	  os << "CommQoSMetrics(";
	  std::vector<std::string>::const_iterator metricNamesIt;
	  std::vector<std::string> metricNamesList = getMetricNamesCopy();
	  for(metricNamesIt=metricNamesList.begin(); metricNamesIt!=metricNamesList.end(); metricNamesIt++) {
	  	os << *metricNamesIt << " ";
	  }
	  std::vector<double>::const_iterator valuesIt;
	  std::vector<double> valuesList = getValuesCopy();
	  for(valuesIt=valuesList.begin(); valuesIt!=valuesList.end(); valuesIt++) {
	  	os << *valuesIt << " ";
	  }
	  os << ") ";
	}
	
	// convert to xml stream
	void CommQoSMetricsCore::to_xml(std::ostream &os, const std::string &indent) const {
		size_t counter = 0;
		
		std::vector<std::string>::const_iterator metricNamesIt;
		std::vector<std::string> metricNamesList = getMetricNamesCopy();
		counter = 0;
		os << indent << "<metricNamesList n=\"" << metricNamesList.size() << "\">";
		for(metricNamesIt=metricNamesList.begin(); metricNamesIt!=metricNamesList.end(); metricNamesIt++) {
			os << indent << "<metricNames i=\"" << counter++ << "\">" << *metricNamesIt << "</metricNames>";
		}
		os << indent << "</metricNamesList>";
		std::vector<double>::const_iterator valuesIt;
		std::vector<double> valuesList = getValuesCopy();
		counter = 0;
		os << indent << "<valuesList n=\"" << valuesList.size() << "\">";
		for(valuesIt=valuesList.begin(); valuesIt!=valuesList.end(); valuesIt++) {
			os << indent << "<values i=\"" << counter++ << "\">" << *valuesIt << "</values>";
		}
		os << indent << "</valuesList>";
	}
	
	// restore from xml stream
	void CommQoSMetricsCore::from_xml(std::istream &is) {
		size_t counter = 0;
		
		static const Smart::KnuthMorrisPratt kmp_metricNamesList("<metricNamesList n=\"");
		static const Smart::KnuthMorrisPratt kmp_metricNames("\">");
		static const Smart::KnuthMorrisPratt kmp_valuesList("<valuesList n=\"");
		static const Smart::KnuthMorrisPratt kmp_values("\">");
		
		if(kmp_metricNamesList.search(is)) {
			size_t numberElements;
			is >> numberElements;
			std::string metricNamesItem;
			std::vector<std::string> metricNamesList;
			kmp_metricNames.search(is);
			for(counter=0; counter<numberElements; counter++) {
				if(kmp_metricNames.search(is)) {
					is >> metricNamesItem;
					metricNamesList.push_back(metricNamesItem);
				}
			}
			setMetricNames(metricNamesList);
		}
		if(kmp_valuesList.search(is)) {
			size_t numberElements;
			is >> numberElements;
			double valuesItem;
			std::vector<double> valuesList;
			kmp_values.search(is);
			for(counter=0; counter<numberElements; counter++) {
				if(kmp_values.search(is)) {
					is >> valuesItem;
					valuesList.push_back(valuesItem);
				}
			}
			setValues(valuesList);
		}
	}
	
	
	void CommQoSMetricsCore::get(ACE_Message_Block *&msg) const
	{
		// start with a default internal buffer size(will automatically grow if needed)
		ACE_OutputCDR cdr(ACE_DEFAULT_CDR_BUFSIZE);
		
		CommRoQMEObjectsIDL::HashList hashes;
		getAllHashValues(hashes);
		cdr << static_cast<ACE_CDR::Long>(hashes.size());
		for(CommRoQMEObjectsIDL::HashList::const_iterator it=hashes.begin(); it!=hashes.end(); it++)
		{
			cdr << ACE_CString(it->c_str());
		}
		
		/**
		 * Here the actual serialization takes place using the OutputCDR serialiazion operator<<
		 * (see CommQoSMetricsSerialization.hh)
		 */
		cdr << idl_CommQoSMetrics;
		
	#ifdef ENABLE_HASH
		ACE_CDR::ULong data_hash = generateDataHash(idl_CommQoSMetrics);
		cdr << data_hash;
		// std::cout << "CommQoSMetricsCore: current data hash: " << data_hash << std::endl;
	#endif
		
		// return a shallow copy of the serialized message 
		// (no data is actually copied, only the internal reference counter is incremented)
		// in order to prevent memory leaks the caller of this get(msg) method must
		// manually free the memory by calling the release() method of the message block msg
		msg = cdr.begin()->duplicate();
	}
	
	void CommQoSMetricsCore::set(const ACE_Message_Block *msg)
	{
		ACE_InputCDR cdr(msg);
	
		CommRoQMEObjectsIDL::HashList hashes;
		ACE_CDR::Long hashes_size;
		cdr >> hashes_size;
		for(int i=0; i<hashes_size; ++i) 
		{
			ACE_CString hash;
			cdr >> hash;
			hashes.push_back(hash.c_str());
		}
		checkAllHashValues(hashes);
		
		/**
		 * Here the actual de-serialization takes place using the InputCDR serialiazion operator>>
		 * (see CommQoSMetricsSerialization.hh)
		 */
		cdr >> idl_CommQoSMetrics;
		
	#ifdef ENABLE_HASH
		ACE_CDR::Long data_hash;
		cdr >> data_hash;
		ACE_CDR::Long own_hash = generateDataHash(idl_CommQoSMetrics);
		assert(data_hash == own_hash);
		// std::cout << "CommQoSMetricsCore: own data hash: " << own_hash << "; received data hash: " << data_hash << std::endl;
	#endif
	}
	
} /* namespace CommRoQMEObjects */
