//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Christian Schlegel (schlegel@hs-ulm.de)
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#ifndef HASH_HH
#define HASH_HH

#include <string>
#include <list>

namespace CommRoQMEObjectsIDL
{
	const char * const REPO_HASH = "22f3305ed086ba6ae82b500188a2aca1";
	typedef std::list<std::string> HashList;
};

#endif
