//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Christian Schlegel (schlegel@hs-ulm.de)
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// This file is generated once. Modify this file to your needs. 
// If you want the toolchain to re-generate this file, please 
// delete it before running the code generator.
//--------------------------------------------------------------------------
#ifndef _BASEBUMPEREVENTHANDLER_USER_HH
#define _BASEBUMPEREVENTHANDLER_USER_HH
	
#include "smartSoft.hh"
#include "BaseBumperEventHandlerCore.hh"
#include <RoqmeWriterImpl.h>

class BaseBumperEventHandler : public BaseBumperEventHandlerCore
{
private:
	void handleEvent(const CHS::EventId id, const CommBasicObjects::CommBumperEventResult &r) throw();

	CHS::SmartMutex lock;
	CommBasicObjects::CommBumperEventResult curentRes;

public:
	CommBasicObjects::CommBumperEventResult getCurrentEventResult();

private:
	Roqme::RoqmeEventWriter eventWr;
};
	
#endif
