//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Christian Schlegel (schlegel@hs-ulm.de)
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// This file is generated once. Modify this file to your needs. 
// If you want the toolchain to re-generate this file, please 
// delete it before running the code generator.
//--------------------------------------------------------------------------
#include "KbEventHandler.hh"
#include "SmartRoQMEMetricsProvider.hh"
#include <iostream>

void KbEventHandler::handleEvent(const CHS::EventId id, const CommBasicObjects::CommKBEventResult &r) throw() 
{
	std::cout << "KbEventHandler event handler: event received: " << std::endl;

	try
	{
		RoqmeDDSTopics::RoqmeEnumContext kbContext;
		if(id == COMP->jobKbEventID)
		{
			kbContext.name("JobState");
			kbContext.value().push_back(r.getFormatedResult());
			enumWr.write(kbContext);
			std::cout<<"Job State published: "<<r.getFormatedResult()<<std::endl;
		}
		else if (id == COMP->robotKbEventID)
		{
			kbContext.name("RobotState");
			kbContext.value().push_back(r.getFormatedResult());
			enumWr.write(kbContext);
			std::cout<<"Robot State published: "<<r.getFormatedResult()<<std::endl;
		}
		else if (id == COMP->personKbEventID){
			kbContext.name("PersonState");
			kbContext.value().push_back(r.getFormatedResult());
			enumWr.write(kbContext);
			std::cout<<"Person State published: "<<r.getFormatedResult()<<std::endl;
		}
		else
		{
			std::cout<<"unkown event, this should not have happend!"<<std::endl;
		}
	}
	catch(Roqme::RoqmeDDSException& e)
	{
		std::cerr << e.what() << std::endl;
	}

	CHS::SmartGuard g(this->lock);
	this->curentRes = r;
}


CommBasicObjects::CommKBEventResult KbEventHandler::getCurrentEventResult(){
	CHS::SmartGuard g(this->lock);
	return this->curentRes;
}
