#--------------------------------------------------------------------------
# Code generated by the SmartSoft MDSD Toolchain
# The SmartSoft Toolchain has been developed by:
#  
# Christian Schlegel (schlegel@hs-ulm.de)
# University of Applied Sciences Ulm
# Prittwitzstr. 10
# 89075 Ulm (Germany)
#
# Information about the SmartSoft MDSD Toolchain is available at:
# www.servicerobotik-ulm.de
#
# Please do not modify this file. It will be re-generated
# running the code generator.
#--------------------------------------------------------------------------

# set-up include directories including all referenced projects
INCLUDE_DIRECTORIES(${USER_INCLUDES})

IF(EXISTS ${PROJECT_SOURCE_DIR}/src-gen/SmartModuleLibrary.cmake)
	INCLUDE(${PROJECT_SOURCE_DIR}/src-gen/SmartModuleLibrary.cmake)
ENDIF(EXISTS ${PROJECT_SOURCE_DIR}/src-gen/SmartModuleLibrary.cmake)

# set-up header files and source files to be compiled
FILE(GLOB COMP_HDRS src/*.hh src-gen/*.hh)
FILE(GLOB COMP_SRCS src/*.cc src-gen/*.cc)

LIST(APPEND USER_SRCS ${COMP_HDRS})
LIST(APPEND USER_SRCS ${COMP_SRCS})

SMART_COMPONENT_ADD_EXECUTABLE(${PROJECT_NAME})

SMART_COMPONENT_INSTALL(${PROJECT_NAME})
