#--------------------------------------------------------------------------
# Code generated by the SmartSoft MDSD Toolchain
# The SmartSoft Toolchain has been developed by:
#  
# Christian Schlegel (schlegel@hs-ulm.de)
# University of Applied Sciences Ulm
# Prittwitzstr. 10
# 89075 Ulm (Germany)
#
# Information about the SmartSoft MDSD Toolchain is available at:
# www.servicerobotik-ulm.de
#
# Please do not modify this file. It will be re-generated
# running the code generator.
#--------------------------------------------------------------------------
CMAKE_MINIMUM_REQUIRED(VERSION 2.8.7)
#TODO remove ace in verion 6.0.1
SET(SMARTSOFT_DEBS "libsmartsoftkernelace (>=2.0.0), libace-6.0.1 (>=6.0.1)| libace-6.0.3, libsmartproperty, libcommbasicobjects (>=1.0.0), libcommroqmeobjects (>=1.0.0), ")

MESSAGE("SMARTSOFT_DEBS is: ${SMARTSOFT_DEBS}")
CONFIGURE_FILE(${CMAKE_CURRENT_SOURCE_DIR}/../debian/control.user ${CMAKE_CURRENT_SOURCE_DIR}/../debian/control @ONLY)
