//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Christian Schlegel (schlegel@hs-ulm.de)
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#ifndef _KBEVENTHANDLER_HH
#define _KBEVENTHANDLER_HH

	#include "smartSoft.hh"

// include communication objects
#include <CommBasicObjects/CommBaseState.hh>
#include <CommBasicObjects/CommBumperEventParameter.hh>
#include <CommBasicObjects/CommBumperEventResult.hh>
#include <CommBasicObjects/CommKBEventParam.hh>
#include <CommBasicObjects/CommKBEventResult.hh>
#include <CommRoQMEObjects/CommQoSMetrics.hh>
	
class KbEventHandlerCore : public CHS::EventHandler<CommBasicObjects::CommKBEventResult>
{
public:
	void handleEvent(const CHS::EventId id, const CommBasicObjects::CommKBEventResult &r) throw() { };	
};
#endif
