//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Christian Schlegel (schlegel@hs-ulm.de)
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#include <iostream>
#include "SmartRoQMEMetricsProvider.hh"
	
	
SmartRoQMEMetricsProvider SmartRoQMEMetricsProvider::_smartRoQMEMetricsProvider;
	
int main(int argc, char *argv[])
{
	std::cout << "main...\n";
	SmartRoQMEMetricsProvider::instance()->init(argc, argv);
	SmartRoQMEMetricsProvider::instance()->run();
	std::cout << "... main() end. return 0." << std::endl;
	return 0;
}
