//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Christian Schlegel (schlegel@hs-ulm.de)
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#ifndef _MONITORINGTASK_CORE_HH
#define _MONITORINGTASK_CORE_HH
	
#include "smartSoft.hh"

#include "MonitoringTaskTimerCore.hh"
	
class MonitoringTaskCore : public CHS::ManagedTask
{
private:
	MonitoringTaskTimerCore timer;
public:
	MonitoringTaskCore(CHS::SmartComponent *comp)
	:	CHS::ManagedTask(comp)
, timer()
	{  }
	virtual ~MonitoringTaskCore()
	{  }

	// svc is overloaded to implement periodic behavior
	int svc();
};
#endif
