//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Christian Schlegel (schlegel@hs-ulm.de)
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#include "MonitoringTaskCore.hh"
#include "SmartRoQMEMetricsProvider.hh"

int MonitoringTaskCore::svc()
{
	bool stop = false;

	if (this->on_entry() != 0)
	{
		stop = true;
	}
	else
	{
		timer.start();
	}

	while (!test_cancel() && !stop)
	{
		if (this->on_execute() != 0)
		{
			stop = true;
		}
		else
		{
			this->timer.waitTimer();
		}
	}

	timer.stop();

	return this->on_exit();
}
