#--------------------------------------------------------------------------
# Code generated by the SmartSoft MDSD Toolchain
# The SmartSoft Toolchain has been developed by:
#  
# Christian Schlegel (schlegel@hs-ulm.de)
# University of Applied Sciences Ulm
# Prittwitzstr. 10
# 89075 Ulm (Germany)
#
# Information about the SmartSoft MDSD Toolchain is available at:
# www.servicerobotik-ulm.de
#
# Please do not modify this file. It will be re-generated
# running the code generator.
#--------------------------------------------------------------------------

FIND_FILE(SMART_MACROS SmartMacros.cmake PATHS $ENV{SMART_ROOT_ACE} /opt/smartSoftAce)
INCLUDE(${SMART_MACROS})
FIND_FILE(SMART_REGISTRY SmartRegistry.cmake PATHS $ENV{SMART_ROOT_ACE} /opt/smartSoftAce)
INCLUDE(${SMART_REGISTRY})

SMART_COMPONENT_PROJECT(SmartRoQMEMetricsProvider)

SMART_COMPONENT_BUILD_DEBIAN_PACKAGE(${PROJECT_NAME} 1.0.0)

SET(CMAKE_INSTALL_RPATH "${CMAKE_INSTALL_PREFIX}/lib")

# find SmartSoft package
FIND_SMARTSOFT(2.1.0)

# these are the default includes (add additional "LIST(APPEND USER_INCLUDES ...)" and "LIST(APPEND USER_LIBS ...)") for custom dependencies
LIST(APPEND USER_INCLUDES "${PROJECT_SOURCE_DIR}/src" "${PROJECT_SOURCE_DIR}/src-gen" ${SMARTSOFT_INCLUDE_DIRS})
LIST(APPEND USER_LIBS ${SMARTSOFT_LIBRARIES})

#CommBasicObjects:
SMART_FIND_PACKAGE(CommBasicObjects 1.0.0)
LIST(APPEND USER_INCLUDES ${COMMBASICOBJECTS_INCLUDE_DIRS})
LIST(APPEND USER_LIBS ${COMMBASICOBJECTS_LIBRARIES})

#CommRoQMEObjects:
SMART_FIND_PACKAGE(CommRoQMEObjects 1.0.0)
LIST(APPEND USER_INCLUDES ${COMMROQMEOBJECTS_INCLUDE_DIRS})
LIST(APPEND USER_LIBS ${COMMROQMEOBJECTS_LIBRARIES})

