//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Christian Schlegel (schlegel@hs-ulm.de)
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#ifndef _SMARTROQMEMETRICSPROVIDERIMPL_HH
#define _SMARTROQMEMETRICSPROVIDERIMPL_HH

#include <smartSoft.hh>

class SmartRoQMEMetricsProviderImpl : public CHS::SmartComponent {
public:
	SmartRoQMEMetricsProviderImpl(const std::string &componentName, int & argc, char ** argv);
	virtual ~SmartRoQMEMetricsProviderImpl();

	CHS::StatusCode run(void);
	void closeAllAssociatedTasks(const int &taskShutdownTimeLimit);
	void cleanUpComponentResources();
};

#endif
