//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Christian Schlegel (schlegel@hs-ulm.de)
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#ifndef _SMARTSTATESLAVE_HH
#define _SMARTSTATESLAVE_HH
		
	#include "smartSoft.hh"
	
	class SmartStateChangeHandlerCore : public CHS::StateChangeHandler
	{
	public:
		void handleEnterState(const std::string & substate) throw() { };
		void handleQuitState(const std::string & substate) throw() { };
	};
	#endif
