//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Christian Schlegel (schlegel@hs-ulm.de)
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// This file is generated once. Modify this file to your needs. 
// If you want the toolchain to re-generate this file, please 
// delete it before running the code generator.
//--------------------------------------------------------------------------
#ifndef COMMROQMEOBJECTS_COMMQOSMETRICS_H_
#define COMMROQMEOBJECTS_COMMQOSMETRICS_H_

#include "CommRoQMEObjects/CommQoSMetricsCore.hh"

namespace CommRoQMEObjects {
		
class CommQoSMetrics : public CommQoSMetricsCore {
	public:
		// default constructors
		CommQoSMetrics();
		
		/**
		 * Constructor to set all values.
		 * NOTE that you have to keep this constructor consistent with the model!
		 * Use  at your own choice.
		 *
		 * The preferred way to set values for initialization is:
		 *      CommRepository::MyCommObject obj;
		 *      obj.setX(1).setY(2).setZ(3)...;
		 */
		// CommQoSMetrics(const std::vector<std::string> &metricNames, const std::vector<std::string> &values);
		
		CommQoSMetrics(const CommQoSMetricsCore &commQoSMetrics);
		CommQoSMetrics(const DATATYPE &commQoSMetrics);
		virtual ~CommQoSMetrics();
		
		// use framework specific getter and setter methods from core (base) class
		using CommQoSMetricsCore::get;
		using CommQoSMetricsCore::set;
		
		//
		// feel free to add customized methods here
		//
};

inline std::ostream &operator<<(std::ostream &os, const CommQoSMetrics &co)
{
	co.to_ostream(os);
	return os;
}
	
} /* namespace CommRoQMEObjects */
#endif /* COMMROQMEOBJECTS_COMMQOSMETRICS_H_ */
