#--------------------------------------------------------------------------
# Code generated by the SmartSoft MDSD Toolchain
# The SmartSoft Toolchain has been developed by:
#  
# Christian Schlegel (schlegel@hs-ulm.de)
# University of Applied Sciences Ulm
# Prittwitzstr. 10
# 89075 Ulm (Germany)
#
# Information about the SmartSoft MDSD Toolchain is available at:
# www.servicerobotik-ulm.de
#
# Please do not modify this file. It will be re-generated
# running the code generator.
#--------------------------------------------------------------------------
# set-up include directories including all referenced projects
INCLUDE_DIRECTORIES(${USER_INCLUDES})

# set-up header files and source files to be compiled
FILE(GLOB HDRS src/CommRoQMEObjects/*.hh src-gen/CommRoQMEObjects/*.hh)
FILE(GLOB SRCS src/CommRoQMEObjects/*.cc src-gen/CommRoQMEObjects/*.cc)

SMART_COMMOBJECT_GENERATE_HASH()

SMART_COMMOBJECT_ADD_LIBRARY(${PROJECT_NAME})

SMART_COMMOBJECT_INSTALL(${PROJECT_NAME})
