#--------------------------------------------------------------------------
# Code generated by the SmartSoft MDSD Toolchain
# The SmartSoft Toolchain has been developed by:
#  
# Christian Schlegel (schlegel@hs-ulm.de)
# University of Applied Sciences Ulm
# Prittwitzstr. 10
# 89075 Ulm (Germany)
#
# Information about the SmartSoft MDSD Toolchain is available at:
# www.servicerobotik-ulm.de
#
# Please do not modify this file. It will be re-generated
# running the code generator.
#--------------------------------------------------------------------------
FIND_FILE(SMART_MACROS SmartMacros.cmake PATHS $ENV{SMART_ROOT_ACE} /opt/smartSoftAce)
INCLUDE(${SMART_MACROS})
FIND_FILE(SMART_REGISTRY SmartRegistry.cmake PATHS $ENV{SMART_ROOT_ACE} /opt/smartSoftAce)
INCLUDE(${SMART_REGISTRY})

SMART_COMMOBJECT_PROJECT(CommRoQMEObjects)

SMART_VERSION(1.0.0)

SMART_COMMOBJECT_BUILD_DEBIAN_PACKAGE(${PROJECT_NAME} ${PACKAGE_VERSION_STRING})

# each comm-obj depend on the ACE middleware library
FIND_PACKAGE(ACE 6.0.2 PATHS $ENV{SMART_ROOT_ACE} /opt/smartSoftAce)
LIST(APPEND USER_INCLUDES ${ACE_INCLUDE_DIRS})
LIST(APPEND USER_LIBS ${ACE_LIBRARIES})

# CommRoQMEObjects depends on the SmartXml utility (for xml parsing in comm objects)
SMART_FIND_PACKAGE(SmartXml 1.0.0)
LIST(APPEND USER_INCLUDES ${SMARTXML_INCLUDE_DIRS})
LIST(APPEND USER_LIBS ${SMARTXML_LIBRARIES})

# project specific include directories
LIST(APPEND USER_INCLUDES "${PROJECT_SOURCE_DIR}/src")
LIST(APPEND USER_INCLUDES "${PROJECT_SOURCE_DIR}/src-gen")

